{
  Partial translation of WinIOCtl.h
  Translated 1.11.2009 by JLB Industries
}
unit WinIOCtl;

interface

const
  FILE_DEVICE_DISK = $00000007;
  FILE_DEVICE_MASS_STORAGE = $0000002d;
  FILE_DEVICE_FILE_SYSTEM = $00000009;

  METHOD_BUFFERED = 0;

  IOCTL_DISK_BASE = FILE_DEVICE_DISK;
  IOCTL_STORAGE_BASE = FILE_DEVICE_MASS_STORAGE;

  //File access
  FILE_ANY_ACCESS = 0;
  FILE_SPECIAL_ACCESS = FILE_ANY_ACCESS;
  FILE_READ_ACCESS = $0001; // file & pipe
  FILE_WRITE_ACCESS = $0002; // file & pipe

  //IOCTL FLAGS
  IOCTL_DISK_GET_DRIVE_GEOMETRY  = (IOCTL_DISK_BASE shl 16) or ($0000 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_GET_PARTITION_INFO = (IOCTL_DISK_BASE shl 16) or ($0001 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_DISK_SET_PARTITION_INFO = (IOCTL_DISK_BASE shl 16) or ($0002 shl 2) or (METHOD_BUFFERED) or ((FILE_READ_ACCESS or FILE_WRITE_ACCESS) shl 14);
  IOCTL_DISK_GET_DRIVE_LAYOUT = (IOCTL_DISK_BASE shl 16) or ($0003 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_DISK_SET_DRIVE_LAYOUT = (IOCTL_DISK_BASE shl 16) or ($0004 shl 2) or (METHOD_BUFFERED) or ((FILE_READ_ACCESS or FILE_WRITE_ACCESS) shl 14);
  IOCTL_DISK_VERIFY = (IOCTL_DISK_BASE shl 16) or ($0005 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_FORMAT_TRACKS = (IOCTL_DISK_BASE shl 16) or ($0006 shl 2) or (METHOD_BUFFERED) or ((FILE_READ_ACCESS or FILE_WRITE_ACCESS) shl 14);
  IOCTL_DISK_REASSIGN_BLOCKS = (IOCTL_DISK_BASE shl 16) or ($0007 shl 2) or (METHOD_BUFFERED) or ((FILE_READ_ACCESS or FILE_WRITE_ACCESS) shl 14);
  IOCTL_DISK_PERFORMANCE = (IOCTL_DISK_BASE shl 16) or ($0008 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_IS_WRITABLE = (IOCTL_DISK_BASE shl 16) or ($0009 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_LOGGING = (IOCTL_DISK_BASE shl 16) or ($000a shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_FORMAT_TRACKS_EX = (IOCTL_DISK_BASE shl 16) or ($000b shl 2) or (METHOD_BUFFERED) or ((FILE_READ_ACCESS or FILE_WRITE_ACCESS) shl 14);
  IOCTL_DISK_HISTOGRAM_STRUCTURE = (IOCTL_DISK_BASE shl 16) or ($000c shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_HISTOGRAM_DATA = (IOCTL_DISK_BASE shl 16) or ($000d shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_HISTOGRAM_RESET = (IOCTL_DISK_BASE shl 16) or ($000e shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_REQUEST_STRUCTURE = (IOCTL_DISK_BASE shl 16) or ($000f shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_REQUEST_DATA = (IOCTL_DISK_BASE shl 16) or ($0010 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_DISK_PERFORMANCE_OFF = (IOCTL_DISK_BASE shl 16) or ($0018 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);

  //MASS STORAGE DEVICES FLAGS
  IOCTL_STORAGE_CHECK_VERIFY = (IOCTL_STORAGE_BASE shl 16) or ($0200 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_CHECK_VERIFY2 = (IOCTL_STORAGE_BASE shl 16) or ($0200 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_MEDIA_REMOVAL = (IOCTL_STORAGE_BASE shl 16) or ($0201 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_EJECT_MEDIA = (IOCTL_STORAGE_BASE shl 16) or ($0202 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_LOAD_MEDIA = (IOCTL_STORAGE_BASE shl 16) or ($0203 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_LOAD_MEDIA2 = (IOCTL_STORAGE_BASE shl 16) or ($0203 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_RESERVE = (IOCTL_STORAGE_BASE shl 16) or ($0204 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_RELEASE = (IOCTL_STORAGE_BASE shl 16) or ($0205 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_FIND_NEW_DEVICES = (IOCTL_STORAGE_BASE shl 16) or ($0206 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);

  IOCTL_STORAGE_EJECTION_CONTROL = (IOCTL_STORAGE_BASE shl 16) or ($0250 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_MCN_CONTROL = (IOCTL_STORAGE_BASE shl 16) or ($0251 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);

  IOCTL_STORAGE_GET_MEDIA_TYPES = (IOCTL_STORAGE_BASE shl 16) or ($0300 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_GET_MEDIA_TYPES_EX = (IOCTL_STORAGE_BASE shl 16) or ($0301 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER = (IOCTL_STORAGE_BASE shl 16) or ($0304 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_GET_HOTPLUG_INFO = (IOCTL_STORAGE_BASE shl 16) or ($0305 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_SET_HOTPLUG_INFO = (IOCTL_STORAGE_BASE shl 16) or ($0306 shl 2) or (METHOD_BUFFERED) or ((FILE_READ_ACCESS or FILE_WRITE_ACCESS) shl 14);

  IOCTL_STORAGE_RESET_BUS = (IOCTL_STORAGE_BASE shl 16) or ($0400 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_RESET_DEVICE = (IOCTL_STORAGE_BASE shl 16) or ($0401 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);
  IOCTL_STORAGE_BREAK_RESERVATION = (IOCTL_STORAGE_BASE shl 16) or ($0405 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);

  IOCTL_STORAGE_GET_DEVICE_NUMBER = (IOCTL_STORAGE_BASE shl 16) or ($0420 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_PREDICT_FAILURE = (IOCTL_STORAGE_BASE shl 16) or ($0440 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  IOCTL_STORAGE_READ_CAPACITY = (IOCTL_STORAGE_BASE shl 16) or ($0450 shl 2) or (METHOD_BUFFERED) or (FILE_READ_ACCESS shl 14);

  FSCTL_LOCK_VOLUME = (FILE_DEVICE_FILE_SYSTEM shl 16) or (6 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  FSCTL_UNLOCK_VOLUME = (FILE_DEVICE_FILE_SYSTEM shl 16) or (7 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);
  FSCTL_DISMOUNT_VOLUME = (FILE_DEVICE_FILE_SYSTEM shl 16) or (8 shl 2) or (METHOD_BUFFERED) or (FILE_ANY_ACCESS shl 14);

implementation
end.
